/**
 * 从 compass 的 MAP_MARKERS(5.4MB)提取赐福坐标 → 精简 pins 文件(~30KB)。
 * 运行:npx tsx scripts/extract-grace-pins.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { MAP_MARKERS } from '../_reference/elden-ring-compass/packages/data/src/generated/markers.ts';

const pins = new Map<number, { entityId: number; mapId: string; x: number; z: number }>();
for (const marker of MAP_MARKERS) {
  if (marker.category !== 'grace') continue;
  if (!pins.has(marker.entityId)) {
    pins.set(marker.entityId, {
      entityId: marker.entityId,
      mapId: marker.mapId,
      x: Math.round(marker.x * 10) / 10,
      z: Math.round(marker.z * 10) / 10,
    });
  }
}

const rows = [...pins.values()];
const out = `// @generated by scripts/extract-grace-pins.ts — 从 compass MAP_MARKERS 提取的赐福坐标。
export interface GracePin {
  readonly entityId: number;
  readonly mapId: string;
  readonly x: number;
  readonly z: number;
}

export const GRACE_PINS: readonly GracePin[] = ${JSON.stringify(rows)};
`;
writeFileSync(join(import.meta.dirname, '../src/renderer/src/data/generated/grace-pins.ts'), out, 'utf-8');
console.log(`赐福坐标 ${rows.length} 条已写出`);
