/** 从 compass MAP_MARKERS 提取带名字的 NPC 点位。运行:npx tsx scripts/extract-npc-pins.ts */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { MAP_MARKERS } from '../_reference/elden-ring-compass/packages/data/src/generated/markers.ts';

const seen = new Map<string, { mapId: string; x: number; z: number; n: string }>();
for (const m of MAP_MARKERS) {
  if (m.category !== 'npc' || !m.displayName) continue;
  const key = `${m.displayName}|${m.mapId}|${Math.round(m.x / 40)}|${Math.round(m.z / 40)}`;
  if (!seen.has(key)) {
    seen.set(key, { mapId: m.mapId, x: Math.round(m.x * 10) / 10, z: Math.round(m.z * 10) / 10, n: m.displayName });
  }
}
const rows = [...seen.values()];
console.log(`NPC 点位 ${rows.length} 条(去重后)`);
const out = `// @generated by scripts/extract-npc-pins.ts — compass MAP_MARKERS 中带名字的 NPC 点位。
export interface NpcPin {
  readonly mapId: string;
  readonly x: number;
  readonly z: number;
  readonly n: string;
}

export const NPC_PINS: readonly NpcPin[] = ${JSON.stringify(rows)};
`;
writeFileSync(join(import.meta.dirname, '../src/renderer/src/data/generated/npc-pins.ts'), out, 'utf-8');
